# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  paths:
    include:
    - dockeragent
    - ./*docker.yml

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: 'Build an Push Docker image to ACR'
  inputs:
    command: 'buildAndPush'
    containerRegistry: 'AzureACRSandbox'
    repository : 'devopsbuildagent'
    dockerfile: '**/Dockerfile'
    tags: $(Build.BuildId)

