	USE MASTER;
	CREATE USER [Server-vm01] FROM EXTERNAL PROVIDER
	ALTER ROLE [dbmanager] ADD MEMBER [Server-vm01]
	GO
	CREATE USER [Server-vm02] FROM EXTERNAL PROVIDER
ALTER ROLE [dbmanager] ADD MEMBER [Server-vm02]