CREATE USER <ADF_NAME> FROM EXTERNAL PROVIDER;
ALTER ROLE [db_datawriter] ADD MEMBER <ADF_NAME>;
GRANT SELECT ON SCHEMA::SalesLT TO <ADF_NAME> WITH GRANT OPTION;
GRANT INSERT ON SCHEMA::SalesLT TO <ADF_NAME>;